### ISSUE TITLE
Compartir CSS

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyectos2020-bobadilla#3]
Seria conveniente que las 3 páginas compartan el mismo CSS, de forma tal que si decidis cambiarle algún estilo gráfico, como el fondo de pantalla, cambiando en un solo sitio, se cambie en todos.

**Comment by Manuel-Bobadilla** [comment]
Entendido profe, tenía pensado en vez de hacer solo un css para las 3 paginas, hacer una hoja de estilo que tengan las 3 paginas en donde quede definido todos los apartados que tengan en común, y después, que cada página tenga la suya propia dónde se trabajen los aspectos particulares de las imágenes, textos, etc.
